name: cran-preflight

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      submit:
        description: "Actually submit to CRAN"
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'        # match R in renv.lock
          use-public-rspm: true

      - name: System libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev \
            libgit2-dev libx11-dev pandoc

      - name: Bootstrap tools
        shell: Rscript {0}
        run: |
          install.packages(c("renv","rcmdcheck","pkgbuild","devtools"))

      - name: Restore deps with renv
        shell: Rscript {0}
        run: |
          renv::restore()

      - name: R CMD check (CRAN-like)
        shell: Rscript {0}
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual","--as-cran"), error_on = "error")

      - name: Build source tarball
        id: build
        shell: Rscript {0}
        run: |
          dir.create("dist", showWarnings = FALSE)
          path <- pkgbuild::build(dest_path = "dist")
          writeLines(paste0("tarball=", path), con = Sys.getenv("GITHUB_OUTPUT"))

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: pkg-tarball
          path: dist/*.tar.gz

      # Optional Windows win-builder sanity checks (no CRAN submission)
      - name: Win-builder devel check
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: Rscript {0}
        run: |
          devtools::check_win_devel()   # emails results to Maintainer

  submit:
    needs: check
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.submit }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
          use-public-rspm: true

      - name: Setup tools
        shell: Rscript {0}
        run: |
          install.packages(c("renv","devtools"))
          renv::restore()

      - name: Build and submit to CRAN
        shell: Rscript {0}
        run: |
          dir.create("dist", showWarnings = FALSE)
          tarball <- pkgbuild::build(dest_path = "dist")
          devtools::submit_cran(tarball)
