# .github/workflows/cran-preflight-submit.yml
name: CRAN-Preflight-and-Submit
on:
  workflow_dispatch:
    inputs:
      submit:
        description: "Actually submit to CRAN"
        type: boolean
        default: false

jobs:
  preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual","--as-cran")'
          upload-snapshots: true

      - name: Build source tarball
        id: build
        shell: Rscript {0}
        run: |
          dir.create("dist", showWarnings = FALSE)
          path <- pkgbuild::build(dest_path = "dist")
          writeLines(paste0("tarball=", path), con = Sys.getenv("GITHUB_OUTPUT"))

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: pkg-tarball
          path: dist/*.tar.gz

  submit:
    if: ${{ inputs.submit }}
    needs: preflight
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Build and submit
        shell: Rscript {0}
        run: |
          dir.create("dist", showWarnings = FALSE)
          tarball <- pkgbuild::build(dest_path = "dist")
          devtools::submit_cran(tarball)
