name: R-tests

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      - name: Restore dependencies
        run: Rscript -e 'renv::restore()'

      - name: Run tests
        run: Rscript -e 'testthat::test_dir("tests")'
