name: R-tests
on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
          use-public-rspm: true

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev \
            libgit2-dev libx11-dev pandoc

      - name: Restore with renv
        shell: Rscript {0}
        run: |
          install.packages("renv")
          renv::restore()

      - name: Run tests
        shell: Rscript {0}
        run: |
          testthat::test_dir("tests")
